const STRINGS={
    SIGNUP_FORM:'Signup Form',
    EMAIL:"Email",
    PASSWORD:'Password',
    CONFIRM_PASSWORD:'Confirm Password',
    YOUR_NAME:'Your Name',
    JOB_CATEGORY:'Job Category',
    YOUR_EXPERIENCE_LEVEL:'Your Experience Level',
    GO_TO_LOGIN:'Go To Login',
    SIGNUP:'SignUp',
    FORGOT_PASSSWORD:'Forgot Password',
    ENTER_EMAIL:'Enter Email',
    SEND_EMAIL:'Send Email',
    VERIFY_ACCOUNT:'Verify Account',
    ENTER_CODE:'Enter Code',
    NEW_PASSWORD:'New Password',
    CHANGE_PASSWORD:'Change Password',
    LETS_GO:"Let's go",
    NAME_YOUR_RESUME:'Name Your Resume',
    NEXT:'Next',
    ENTER_RESUME_NAME:'Enter Resume Name',
    CONTACT_DETAILS:'Contact Details',
    EDUCATION_DETAILS:'Education Details',
    EMPLOYEMNT_HISTORY:'Employment History',
    HOBBIES_AND_INTEREST:'Hobbies & Interest',
    PROFESSIONAL_SKILLS:'Professional Skills',
    LANGUAGES:'Languages',
    INDUSTRIAL_EXPOSURE_AS_INTERN:'Industrial Exposure as an Intern',
    AWARD_AND_ACHIEVEMENT:'Award and Achievement',
    OBJECTIVES:'Objectives',
    UPLOAD_IMAGE:'Upload Image',
    UPLOAD_VIDEO:'Upload Video',
    PASTE_YOUTUBE_LINK :'Paste Youtube Link',
    PLEASE_ENTER_YOUTUBE_URL:'Please enter youtube url',
    SUBMIT:'Submit',
    SEND_FEEDBACK:'Send Feedback'
}

export default STRINGS;
